// Code generated by MockGen. DO NOT EDIT.
// Source: service/terraformrefs/terraformrefs.go

// Package mock_service_terraformrefs is a generated GoMock package.
package mock_service_terraformrefs

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// ProcessRepo mocks base method.
func (m *MockServiceInterface) ProcessRepo(owner, name, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRepo", owner, name, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessRepo indicates an expected call of ProcessRepo.
func (mr *MockServiceInterfaceMockRecorder) ProcessRepo(owner, name, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRepo", reflect.TypeOf((*MockServiceInterface)(nil).ProcessRepo), owner, name, branch)
}
